In [1]:
import tensorflow as tf

In [38]:
x = tf.constant(4)

x = tf.constant(4, shape=(1,1), dtype=tf.float32)

x = tf.constant([[1,2,3], [4,5,6]])

x = tf.ones((3,3))
x = tf.zeros((2,3))
x = tf.eye(3)

x = tf.random.normal((3,3), mean=0, stddev=1)
x = tf.random.uniform((1, 3), minval = 0, maxval = 1)

x = tf.range(start=1, limit=10, delta=2)
x = tf.cast(x, dtype=tf.float64)

x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x, y)
z = x + y

z = tf.subtract(x, y)
z = x - y

z = tf.divide(x, y)
z = x / y

z = tf.multiply(x, y)
z = x * y

z = tf.tensordot(x, y, axes=1)
z = tf.reduce_sum(x*y, axis=0)

z = x ** 5

x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x, y)
z = x @ y

x = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])
print(x[:])
print(x[1:])
print(x[::2])
print(x[::-1])

indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)

x = tf.constant([[1,2],[3,4],[5,6]])

print(x[0,:])


x = tf.range(9)
print(x)

x = tf.reshape(x, (3,3))
print(x)

x = tf.transpose(x, perm=[1,0])
print(x)


tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([0 2 4 6], shape=(4,), dtype=int32)
tf.Tensor([7 6 5 4 3 2 1 0], shape=(8,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
